name: Check Nightly Build Status
on:
  workflow_dispatch:
    inputs:
      sha:
        type: string
      release_v:
        type: string
        required: false

permissions:
  contents: write
  issues: write

env:
  GH_TOKEN: ${{ github.token }}
  GH_REPO: duckdb/duckdb
  GH_ISSUE_REPO: ${{ github.repository }}
  sha: ${{ inputs.sha }}
  release_v: ${{ inputs.release_v }}
jobs:
  check-wget:
    name: Check in advance
    runs-on: macos-13
    steps:
      - name: Checkout repo with the scripts
        uses: actions/checkout@v4

      - name: RELEASE Run the script to check extensions
        shell: bash
        run: chmod +x scripts/check_ext.sh && ./scripts/check_ext.sh
      - uses: actions/upload-artifact@v4
        with:
          path: log.csv
