name: Test InvokeCI
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      override_git_describe:
        type: string
      git_ref:
        type: string
      skip_tests:
        type: string
      run_all:
        type: string
      twine_upload:
        type: string

concurrency:
  group: invokeci-${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}-${{ inputs.override_git_describe }}-${{ inputs.git_ref }}-${{ inputs.skip_tests }}
  cancel-in-progress: true

jobs:
  osx:
    runs-on: ubuntu-latest
    steps:
      - run: return 1

  linux-release:
    runs-on: ubuntu-latest
    steps:
      - run: return 0

  windows:
    runs-on: ubuntu-latest
    steps:
      - run: return 0

  python:
    runs-on: ubuntu-latest
    steps:
      - run: return 1
  pyodide:
    runs-on: ubuntu-latest
    steps:
      - run: return 0
  R:
    runs-on: ubuntu-latest
    steps:
      - run: return 0
  Wasm:
    runs-on: ubuntu-latest
    steps:
      - run: return 0
  
  static-libraries:
    runs-on: ubuntu-latest
    steps:
      - run: return 1
      
  prepare-status:
    runs-on: ubuntu-latest
    needs:
      - osx
      - linux-release
      - windows
      - python
      - pyodide
      - R
      - Wasm
      - static-libraries
    if: success()
    outputs:
      is-success: ${{ steps.set-output.outputs.success }}
    steps:
      - id: set-output
        run:
          echo "success=true" >> $GITHUB_OUTPUT

  notify-external-repos-main:
    runs-on: ubuntu-latest
    needs:
      - prepare-status
    if: ${{ inputs.git_ref == '' }} 
    steps:
      - run: echo ${{ needs.prepare-status.outputs.is-success }}

  notify-specific-branch-on-external-repos:
    runs-on: ubuntu-latest
    needs:
      - prepare-status
    if: ${{ inputs.git_ref != '' }} 
    steps:
      - run: echo ${{ needs.prepare-status.outputs.is-success }}
