name: Trigger Nightly Build Status Check
on:
  push:
  schedule:
    - cron: '0 9 * * *' # runs at 11am CEST (replace the las * with 1-5 to trigger only on working days)
  workflow_dispatch:
    inputs:
        branch:
            type: string
        event:
            type: string
        should_publish:
            type: string
permissions:
  contents: write
  issues: write

jobs:
    on-workflow-dispatch:
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: hmeriann/duckdb-build-status/.github/workflows/NightlyBuildsCheck.yml@call-from-invoke
        with:
            branch: ${{ inputs.branch }}
            event: ${{ inputs.event }}
            should_publish: ${{ inputs.should_publish }}

    on-workflow-call:
        if: ${{ github.event_name != 'workflow_dispatch' }}
        runs-on: ubuntu-latest
        env:
            PAT_USER: ${{ secrets.PAT_USER }}
            PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        strategy:
            matrix:
                config: [{"branch": "main", "event": "repository_dispatch", "should_publish": "true"}, {"branch": "v1.2-histrionicus", "event": "workflow_dispatch", "should_publish": "true"}, ]
        steps:
            - name: Run Nightly build status
              run: |
                # export URL="https://api.github.com/repos/hmeriann/duckdb-build-status/.github/workflows/NightlyBuildsCheck.yml"
                # export DATA="${{ matrix.config }}"
                # curl -v -XPOST -u "${PAT_USER}:${PAT_TOKEN}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" $URL --data "$DATA"
                curl -L \
                    -X POST \
                    -H "Accept: application/vnd.github+json" \
                    -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
                    -H "X-GitHub-Api-Version: 2022-11-28" \
                    https://api.github.com/repos/${{ secrets.PAT_USER }}/duckdb-build-status/dispatches \
                    -d '{"event_type":"run-nightly-builds-status","client_payload":{"branch": "main", "event": "repository_dispatch", "should_publish": "true"}'