name: Trigger Nightly Build Status Check
on:
  push:
  schedule:
    - cron: '0 9 * * *' # runs at 11am CEST (replace the las * with 1-5 to trigger only on working days)
  workflow_dispatch:
    inputs:
        branch:
            type: string
        event:
            type: string
        should_publish:
            type: string
permissions:
  contents: write
jobs:
    on-workflow-dispatch:
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: hmeriann/duckdb-build-status/.github/workflows/NightlyBuildsCheck.yml@call-from-invoke
        with:
            branch: ${{ inputs.branch }}
            event: ${{ inputs.event }}
            should_publish: ${{ inputs.should_publish }}
        # secrets:
        #     PAT_TOKEN: ${{ secrets.PAT_TOKEN }}

    on-workflow-call:
        strategy:
            matrix:
                config: [{"branch": "main", "event": "repository_dispatch", "should_publish": "true"}, {"branch": "v1.2-histrionicus", "event": "workflow_dispatch", "should_publish": "true"}, ]
        if: ${{ github.event_name != 'workflow_dispatch' }}
        uses: hmeriann/duckdb-build-status/.github/workflows/NightlyBuildsCheck.yml@call-from-invoke
        with:
            branch: ${{ matrix.config.branch }}
            event: ${{ matrix.config.event }}
            should_publish: ${{ matrix.config.should_publish }}
        # secrets:
        #     PAT_TOKEN: ${{ secrets.PAT_TOKEN }}